source 'https://rubygems.org'

gem 'appraisal'

gemspec

gem 'jruby-openssl', :platforms => :jruby

gem 'yard'

# Additional gems that are useful, but not required for development.
gem 'relish', '~> 0.6'
gem 'fuubar'
gem 'fuubar-cucumber'

gem 'redcarpet', '~> 3.5.1', :platforms => :ruby
gem 'github-markup'

group :extras do
  gem 'ruby-debug', :platforms => [:mri_18, :jruby]

  gem 'debugger', :platforms => :mri_19
  gem 'pry'
end
